<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="serviceTests.ReimbursementServiceTests" tests="10" skipped="0" failures="0" errors="0" timestamp="2021-03-02T01:03:43" hostname="DESKTOP-T6NR4LV" time="6.666">
  <properties/>
  <testcase name="get_user()" classname="serviceTests.ReimbursementServiceTests" time="0.92"/>
  <testcase name="get_all_expenses()" classname="serviceTests.ReimbursementServiceTests" time="0.616"/>
  <testcase name="get_all_expenses_illegal_access_exception()" classname="serviceTests.ReimbursementServiceTests" time="0.011"/>
  <testcase name="get_expense()" classname="serviceTests.ReimbursementServiceTests" time="0.297"/>
  <testcase name="get_expense_2()" classname="serviceTests.ReimbursementServiceTests" time="0.314"/>
  <testcase name="get_expense_3()" classname="serviceTests.ReimbursementServiceTests" time="0.3"/>
  <testcase name="update_expense()" classname="serviceTests.ReimbursementServiceTests" time="2.097"/>
  <testcase name="update_expense_2()" classname="serviceTests.ReimbursementServiceTests" time="0.91"/>
  <testcase name="update_expense_3()" classname="serviceTests.ReimbursementServiceTests" time="0.868"/>
  <testcase name="create_expense()" classname="serviceTests.ReimbursementServiceTests" time="0.315"/>
  <system-out><![CDATA[User is not permitted to access all expenses
User is not permitted to access the indicated expense
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
